use_frameworks!
platform :ios, '9.3'

target 'PopupTransitioningDelegate_Example' do
  pod 'PopupTransitioningDelegate', :path => '../'

  target 'PopupTransitioningDelegate_Tests' do
    inherit! :search_paths

    
  end
end
